Numpy: Numerical Python

NumPy and Pandas are essential Python libraries for handling numerical and tabular data efficiently.

In [1]:
import numpy as np

In [2]:
# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
# Creating a 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
# Array Properties
print(arr2.size)
print(arr2.shape)
print(arr1.dtype)

6
(2, 3)
int64


In [5]:
# Generating Array
print(np.zeros((3,3)))
print(np.ones((2,2)))
print(np.arange(1,10,2))
print(np.linspace(1,10,5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [6]:
# Random Array
arr = np.random.rand(3,3)
print(arr)

[[0.77351318 0.72999585 0.58594606]
 [0.40526207 0.76616519 0.24811543]
 [0.43696935 0.93666402 0.60995512]]


In [7]:
# Indexing and Slicing
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0])
print(arr[-1])
print(arr[1:5])

1
8
[2 3 4 5]


In [8]:
# Matrix Operation
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)
print(A - B)
# Element-wise multiplication
print(A * B)
# Matrix multiplication
print(np.dot(A, B))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
