# **Missing Value Iterative Imputer**

### **Import Libraries, Load and Analyze Data and Take 5 Sample to apply Iterative Imputer**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
df = np.round(pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Learning Machine Learning/50_Startups_dataset.csv')[['R&D Spend', 'Administration','Marketing Spend', 'Profit']])
np.random.seed(9)
df = df.sample(5)
df

R&D Spend  Administration  Marketing Spend    Profit
21    78390.0        153774.0         299737.0  111313.0
37    44070.0         51283.0         197030.0   89949.0
2    153442.0        101146.0         407935.0  191050.0
14   119943.0        156548.0         256513.0  132603.0
44    22178.0        154806.0          28335.0   65200.0

### **Select R&D Spend, Administration and Marketing Spend Column**

In [ ]:
df = df.iloc[:,0:-1]
df

R&D Spend  Administration  Marketing Spend
21    78390.0        153774.0         299737.0
37    44070.0         51283.0         197030.0
2    153442.0        101146.0         407935.0
14   119943.0        156548.0         256513.0
44    22178.0        154806.0          28335.0

### **Make one - one from each row NaN**

In [ ]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

/tmp/ipython-input-32-766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipython-input-32-766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipython-input-32-766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [ ]:
df.head()

R&D Spend  Administration  Marketing Spend
21    78390.0        153774.0         299737.0
37        NaN         51283.0         197030.0
2    153442.0        101146.0         407935.0
14   119943.0             NaN         256513.0
44    22178.0        154806.0              NaN

### **Fill NaN with Mean Values**

In [ ]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [ ]:
df0

R&D Spend  Administration  Marketing Spend
21   78390.00       153774.00        299737.00
37   93488.25        51283.00        197030.00
2   153442.00       101146.00        407935.00
14  119943.00       115252.25        256513.00
44   22178.00       154806.00        290303.75

In [ ]:
df1 = df0.copy()

### **Make 1st column Value as NaN**

In [ ]:
df1.iloc[1,0] = np.nan
df1

R&D Spend  Administration  Marketing Spend
21    78390.0       153774.00        299737.00
37        NaN        51283.00        197030.00
2    153442.0       101146.00        407935.00
14   119943.0       115252.25        256513.00
44    22178.0       154806.00        290303.75

In [ ]:
X = df1.iloc[[0,2,3,4],1:3]
X

Administration  Marketing Spend
21       153774.00        299737.00
2        101146.00        407935.00
14       115252.25        256513.00
44       154806.00        290303.75

In [ ]:
y = df.iloc[[0,2,3,4],0]

In [ ]:
y

21     78390.0
2     153442.0
14    119943.0
44     22178.0
Name: R&D Spend, dtype: float64

### **Predict Value**

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df.iloc[1,1:].values.reshape(1, -1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([230216.15069166])

In [ ]:
df1.iloc[1,0] = 230216.15069166

### **Substitute Value**

In [ ]:
df1

R&D Spend  Administration  Marketing Spend
21   78390.000000       153774.00        299737.00
37  230216.150692        51283.00        197030.00
2   153442.000000       101146.00        407935.00
14  119943.000000       115252.25        256513.00
44   22178.000000       154806.00        290303.75

In [ ]:
df1.iloc[3,1] = np.nan
df1

R&D Spend  Administration  Marketing Spend
21   78390.000000        153774.0        299737.00
37  230216.150692         51283.0        197030.00
2   153442.000000        101146.0        407935.00
14  119943.000000             NaN        256513.00
44   22178.000000        154806.0        290303.75

In [ ]:
X = df1.iloc[[0,1,2,4],[0,2]]
X

R&D Spend  Marketing Spend
21   78390.000000        299737.00
37  230216.150692        197030.00
2   153442.000000        407935.00
44   22178.000000        290303.75

In [ ]:
y = df1.iloc[[0,1,2,4],1]
y

21    153774.0
37     51283.0
2     101146.0
44    154806.0
Name: Administration, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

array([113583.09207822])

In [ ]:
df1.iloc[3,1] = 113583.09207822

In [ ]:
df1

R&D Spend  Administration  Marketing Spend
21   78390.000000   153774.000000        299737.00
37  230216.150692    51283.000000        197030.00
2   153442.000000   101146.000000        407935.00
14  119943.000000   113583.092078        256513.00
44   22178.000000   154806.000000        290303.75

In [ ]:
df1.iloc[4,-1] = np.nan
df1

R&D Spend  Administration  Marketing Spend
21   78390.000000   153774.000000         299737.0
37  230216.150692    51283.000000         197030.0
2   153442.000000   101146.000000         407935.0
14  119943.000000   113583.092078         256513.0
44   22178.000000   154806.000000              NaN

In [ ]:
X = df1.iloc[0:4,0:2]
X

R&D Spend  Administration
21   78390.000000   153774.000000
37  230216.150692    51283.000000
2   153442.000000   101146.000000
14  119943.000000   113583.092078

In [ ]:
y = df1.iloc[0:4,-1]
y

21    299737.0
37    197030.0
2     407935.0
14    256513.0
Name: Marketing Spend, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([247960.21037183])

In [ ]:
df1.iloc[4,-1] = 247960.21037183

In [ ]:
df1

R&D Spend  Administration  Marketing Spend
21   78390.000000   153774.000000    299737.000000
37  230216.150692    51283.000000    197030.000000
2   153442.000000   101146.000000    407935.000000
14  119943.000000   113583.092078    256513.000000
44   22178.000000   154806.000000    247960.210372

In [ ]:
df1 - df0

R&D Spend  Administration  Marketing Spend
21       0.000000        0.000000         0.000000
37  136727.900692        0.000000         0.000000
2        0.000000        0.000000         0.000000
14       0.000000    -1669.157922         0.000000
44       0.000000        0.000000    -42343.539628

In [ ]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan
df2

R&D Spend  Administration  Marketing Spend
21    78390.0   153774.000000    299737.000000
37        NaN    51283.000000    197030.000000
2    153442.0   101146.000000    407935.000000
14   119943.0   113583.092078    256513.000000
44    22178.0   154806.000000    247960.210372

In [ ]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([195724.6286988])

In [ ]:
df2.iloc[1,0] = 195724.6286988

In [ ]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([106377.80916521])

In [ ]:
df2.iloc[3,1] = 106377.80916521

In [ ]:
df2.iloc[4,-1] = np.nan
X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([14807.0600415])

In [ ]:
df2.iloc[4,-1] = np.nan
X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([14807.0600415])

In [ ]:
df2.iloc[4,-1] = 14807.0600415

In [ ]:
df2

R&D Spend  Administration  Marketing Spend
21   78390.000000   153774.000000    299737.000000
37  195724.628699    51283.000000    197030.000000
2   153442.000000   101146.000000    407935.000000
14  119943.000000   106377.809165    256513.000000
44   22178.000000   154806.000000     14807.060042

In [ ]:
df2 -df1

R&D Spend  Administration  Marketing Spend
21      0.000000        0.000000          0.00000
37 -34491.521993        0.000000          0.00000
2       0.000000        0.000000          0.00000
14      0.000000    -7205.282913          0.00000
44      0.000000        0.000000    -233153.15033

In [ ]:
df3 = df2.copy()
df3.iloc[1,0] = np.nan
df3

R&D Spend  Administration  Marketing Spend
21    78390.0   153774.000000    299737.000000
37        NaN    51283.000000    197030.000000
2    153442.0   101146.000000    407935.000000
14   119943.0   106377.809165    256513.000000
44    22178.0   154806.000000     14807.060042

In [ ]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([165578.01710043])

In [ ]:
df3.iloc[1,0] = 165578.01710043